CREATE TABLE PERSON(
	PersonID Int NOT NULL,
    isEmployee CHAR(4) NOT NULL,
    isCustomer CHAR(4) NOT NULL,
	LastName CHAR(25) NOT NULL,
	FirstName CHAR(25) NOT NULL,
	Address CHAR(35) NULL,
	City CHAR(35) NULL,
	State CHAR(2) NULL,
	ZIP CHAR(10) NULL,
	Phone CHAR(12) NOT NULL,
	Email VARCHAR(100) NULL,
    
	CONSTRAINT Person_PK PRIMARY KEY(PersonID)
);
    
    
CREATE TABLE CUSTOMER (
	PersonID Int NOT NULL,
    CreditCardType CHAR(25) NOT NULL,
    CreditCardNumber VARCHAR(30) NOT NULL,
    CreditCardExpirationDate DATE NOT NULL,
    
	CONSTRAINT Customer_PK PRIMARY KEY(PersonID),
	CONSTRAINT CustomerPerson_FK FOREIGN KEY(PersonID) 
		REFERENCES PERSON(PersonID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);


CREATE TABLE EMPLOYEE (
	PersonID Int NOT NULL,
    DateOfHire DATE NOT NULL,
    HourlyPayRate NUMERIC(9,2) NOT NULL,
    
	CONSTRAINT Employee_PK PRIMARY KEY(PersonID),
	CONSTRAINT EmployeePerson_FK FOREIGN KEY(PersonID)
		REFERENCES PERSON(PersonID)
	ON UPDATE NO ACTION
    ON DELETE CASCADE
);


CREATE TABLE SALE (
	SaleID INT NOT NULL,
    SaleDate DATE NOT NULL,
    SubTotal NUMERIC(9,2) NULL,
    Tax NUMERIC(9,2) NULL,
    Total NUMERIC(9,2) NULL,
    CustomerPersonID INT NOT NULL,
    EmployeePersonID INT NOT NULL,
    
	CONSTRAINT Sale_PK PRIMARY KEY(SaleID),
	CONSTRAINT SaleCustomer_FK FOREIGN KEY(CustomerPersonID) 
		REFERENCES CUSTOMER(PersonID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
	CONSTRAINT SaleEmployee_FK FOREIGN KEY(EmployeePersonID) 
		REFERENCES EMPLOYEE(PersonID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);


CREATE TABLE ITEM (
	ItemID INT NOT NULL,
    ItemDescription VARCHAR(255) NOT NULL,
    ReorderPointQuantity INT NULL,
    QuantityOnHand INT NULL,
    ItemPrice NUMERIC(9,2) NOT NULL,
    
	CONSTRAINT Item_PK PRIMARY KEY(ItemID)
);


CREATE TABLE SALE_ITEM (
	SaleID INT NOT NULL,
	SaleItemID INT NOT NULL,
	Quantity INT NOT NULL,
    ItemPrice NUMERIC(9,2) NULL,
    ExtendedPrice NUMERIC(9,2) NULL,
    ItemID INT NOT NULL,
    
	CONSTRAINT SaleItem_PK PRIMARY KEY(SaleID, SaleItemID),
	CONSTRAINT SaleItemSale_FK FOREIGN KEY(SaleID) REFERENCES SALE(SaleID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE,
	CONSTRAINT SaleItemItem_FK FOREIGN KEY(ItemID) REFERENCES ITEM(ItemID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);


CREATE TABLE VENDOR (
	VendorID INT NOT NULL,
    CompanyName VARCHAR(100) NULL,
    ContactLastName CHAR(25) NOT NULL,
    ContactFirstName CHAR(25) NOT NULL,
	Address CHAR(35) NULL,
	City CHAR(35) NULL,
	State CHAR(2) NULL,
	ZIP CHAR(10) NULL,
	Phone CHAR(12) NOT NULL,
	Fax CHAR(12) NULL,
	Email VARCHAR(100) NULL,
    
	CONSTRAINT Vendor_PK PRIMARY KEY(VendorID)
);


CREATE TABLE `ORDER` (
	InvoiceNumber INT NOT NULL,
    DateOrdered DATE NOT NULL,
    DateReceived DATE NULL,
    QuantityOrdered INT NOT NULL,
    ItemCost NUMERIC(9,2) NOT NULL,
    OrderSubTotal NUMERIC(9,2) NOT NULL,
    OrderTax NUMERIC(9,2) NOT NULL,
    OrderTotalCost NUMERIC(9,2) NOT NULL,
	ItemID INT NOT NULL,
	VendorID INT NOT NULL,
    
	CONSTRAINT Order_PK PRIMARY KEY(InvoiceNumber),
	CONSTRAINT OrderItem_FK FOREIGN KEY(ItemID) 
		REFERENCES ITEM(ItemID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
	CONSTRAINT OrderVendor_FK FOREIGN KEY(VendorID) 
		REFERENCES VENDOR(VendorID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);